import { ArtItem, Creator, DropEvent, BlogPost } from "@/types";

export const CREATORS: Creator[] = [
  {
    id: "c-1",
    name: "Aria Sterling",
    handle: "@ariasterling",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    verified: true,
    bio: "Pioneering cyber-surrealism and generative neural sculpture.",
    followersCount: 38400,
    artworksCount: 42,
    bannerImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "c-2",
    name: "Kaelen Vance",
    handle: "@kaelenvance",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    verified: true,
    bio: "Senior 3D lighting director & spatial designer.",
    followersCount: 52100,
    artworksCount: 68,
    bannerImage: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "c-3",
    name: "Elena Rostova",
    handle: "@elena_art",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    verified: true,
    bio: "Chromatographic illusionist exploring multidimensional color theory.",
    followersCount: 29800,
    artworksCount: 31,
    bannerImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
  },
  {
    id: "c-4",
    name: "Darius Thorne",
    handle: "@dthorne_fx",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    verified: true,
    bio: "Procedural geometry architect & interactive web canvas artist.",
    followersCount: 44300,
    artworksCount: 54,
  },
  {
    id: "c-5",
    name: "Zoe Lin",
    handle: "@zoe_matrix",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    verified: true,
    bio: "Cyberpunk photographer capturing Tokyo neon & retro-futuristic nocturnes.",
    followersCount: 61900,
    artworksCount: 77,
  }
];

export const ART_ITEMS: ArtItem[] = [
  {
    id: "art-1",
    title: "Chroma Core Synthesis",
    subtitle: "Iridescent Hyper-Dimensional Artifact",
    description: "A generative real-time particle simulation exploring the refraction of consciousness inside liquid prismatic silicon.",
    priceTk: 1250,
    priceEth: 0.42,
    priceUsd: 1450,
    category: "3D & Cyberpunk",
    imageUrl: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=800&auto=format&fit=crop&q=80",
    creator: CREATORS[0],
    likes: 842,
    edition: { current: 1, total: 25 },
    dominantColor: "#8B5CF6",
    accentColor: "#C084FC",
    tags: ["3D", "Cyberpunk", "Iridescent", "Particle"],
    featured: true,
    trending: true,
    createdAt: "2026-08-15",
  },
  {
    id: "art-2",
    title: "Neo-Kyoto Nocturne",
    subtitle: "Dystopian Neon Streetscape",
    description: "Long exposure cybernetic photography captured in rainfall, highlighting augmented reality projections across steel corridors.",
    priceTk: 980,
    priceEth: 0.31,
    priceUsd: 1120,
    category: "Photography",
    imageUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    creator: CREATORS[4],
    likes: 1240,
    edition: { current: 3, total: 50 },
    dominantColor: "#06B6D4",
    accentColor: "#38BDF8",
    tags: ["Photography", "Cyberpunk", "Neon", "Urban"],
    featured: true,
    trending: true,
    createdAt: "2026-08-20",
  },
  {
    id: "art-3",
    title: "Quantum Fluid Monolith",
    subtitle: "Procedural Flow & Metallic Waves",
    description: "Computational fluid dynamics sculpted with dark obsidian gloss and molten titanium reflections.",
    priceTk: 1650,
    priceEth: 0.58,
    priceUsd: 1950,
    category: "Abstract & Fluid",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    creator: CREATORS[1],
    likes: 673,
    edition: { current: 4, total: 10 },
    dominantColor: "#10B981",
    accentColor: "#34D399",
    tags: ["Abstract", "Fluid", "Metallic", "Minimalist"],
    featured: true,
    createdAt: "2026-08-28",
  },
  {
    id: "art-4",
    title: "Ethereal Mindscape #09",
    subtitle: "Synaptic Neural Dreamscape",
    description: "Generative neural hallucination training weights visualized as floating bioluminescent botanical structures.",
    priceTk: 890,
    priceEth: 0.28,
    priceUsd: 980,
    category: "Generative AI",
    imageUrl: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=800&auto=format&fit=crop&q=80",
    creator: CREATORS[2],
    likes: 512,
    edition: { current: 7, total: 30 },
    dominantColor: "#F43F5E",
    accentColor: "#FB7185",
    tags: ["AI", "Generative", "Bioluminescent", "Flora"],
    trending: true,
    createdAt: "2026-09-01",
  },
  {
    id: "art-5",
    title: "Orbital HUD Interface",
    subtitle: "Spatial Computing Hologram",
    description: "Tactical telemetry interface designed for aerospace teleoperation and high-density orbital tracking.",
    priceTk: 1420,
    priceEth: 0.46,
    priceUsd: 1600,
    category: "Futuristic UI",
    imageUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80",
    creator: CREATORS[3],
    likes: 934,
    edition: { current: 2, total: 15 },
    dominantColor: "#06B6D4",
    accentColor: "#67E8F9",
    tags: ["HUD", "Interface", "Sci-Fi", "Vector"],
    createdAt: "2026-08-10",
  },
  {
    id: "art-6",
    title: "Solar Flare Polygons",
    subtitle: "Parametric Tessellation",
    description: "Dynamic radiant tessellation inspired by high-energy coronal mass ejections from deep solar observation arrays.",
    priceTk: 750,
    priceEth: 0.22,
    priceUsd: 820,
    category: "Abstract & Fluid",
    imageUrl: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800&auto=format&fit=crop&q=80",
    creator: CREATORS[2],
    likes: 429,
    edition: { current: 5, total: 40 },
    dominantColor: "#F59E0B",
    accentColor: "#FBBF24",
    tags: ["Geometric", "Solar", "Parametric", "Gold"],
    createdAt: "2026-08-18",
  },
  {
    id: "art-7",
    title: "Metropolis Cyberpunk 2088",
    subtitle: "High-Altitude Neon Corridor",
    description: "Atmospheric perspective looking down 300 stories onto holographic flight lanes in a rain-slicked mega-structure.",
    priceTk: 1850,
    priceEth: 0.65,
    priceUsd: 2200,
    category: "3D & Cyberpunk",
    imageUrl: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80",
    creator: CREATORS[4],
    likes: 1580,
    edition: { current: 1, total: 8 },
    dominantColor: "#8B5CF6",
    accentColor: "#A78BFA",
    tags: ["Cyberpunk", "Cityscape", "Futuristic", "Render"],
    featured: true,
    trending: true,
    createdAt: "2026-08-05",
  },
  {
    id: "art-8",
    title: "Glass Prism Echo",
    subtitle: "Refractive Light Study",
    description: "Crystalline caustic simulations refracting pure beam dispersion into spectrum bands inside void space.",
    priceTk: 1100,
    priceEth: 0.35,
    priceUsd: 1250,
    category: "Abstract & Fluid",
    imageUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
    creator: CREATORS[1],
    likes: 770,
    edition: { current: 9, total: 20 },
    dominantColor: "#10B981",
    accentColor: "#6EE7B7",
    tags: ["Prism", "Glass", "Caustics", "Minimal"],
    createdAt: "2026-08-22",
  }
];

export const DROP_EVENTS: DropEvent[] = [
  {
    id: "drop-1",
    title: "Vortex Singularity Series",
    description: "Exclusive 1-of-1 collaborative drop featuring live reactive audio stems and holographic 3D asset files.",
    imageUrl: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=800&auto=format&fit=crop&q=80",
    creator: CREATORS[0],
    startsAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    endsAt: new Date(Date.now() + 1000 * 60 * 60 * 36).toISOString(),
    startingBidTk: 2500,
    currentBidTk: 4800,
    totalBids: 19,
    isLive: true,
    rarity: "Legendary",
  },
  {
    id: "drop-2",
    title: "Cybernetic Genesis: Chapter IV",
    description: "High-octane biomechanical armor suits sculpted for open-world metaverse engines.",
    imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    creator: CREATORS[1],
    startsAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    endsAt: new Date(Date.now() + 1000 * 60 * 60 * 18).toISOString(),
    startingBidTk: 1800,
    currentBidTk: 3100,
    totalBids: 14,
    isLive: true,
    rarity: "Epic",
  },
  {
    id: "drop-3",
    title: "Neon Monoliths of Shibuya",
    description: "Archival edition fine-art prints accompanied by cryptographic proof of authenticity.",
    imageUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    creator: CREATORS[4],
    startsAt: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    endsAt: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    startingBidTk: 3000,
    currentBidTk: 3000,
    totalBids: 0,
    isLive: false,
    rarity: "Legendary",
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "blog-1",
    title: "The Architecture of Spatial Computing & Real-time Shaders",
    slug: "architecture-spatial-computing-shaders",
    excerpt: "How next-generation WebGPU and vertex shaders are transforming browser-based interactive 3D portfolios.",
    content: "Spatial computing is no longer confined to heavy native engines. With WebGPU and modern React three pipelines, creators can render million-polygon scenes smoothly directly inside Next.js App Router applications. In this article, we dissect memory management, progressive mesh streaming, and procedural material generation.",
    coverImage: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=800&auto=format&fit=crop&q=80",
    author: {
      name: "Darius Thorne",
      role: "Lead Creative Technologist",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    },
    readTime: "5 min read",
    publishedAt: "2026-08-29",
    category: "Technology",
    tags: ["WebGPU", "3D Art", "Next.js", "Performance"],
  },
  {
    id: "blog-2",
    title: "Color Theory in Generative AI: From Prompts to Palette Harmonies",
    slug: "color-theory-generative-ai",
    excerpt: "Demystifying why certain spectral gradients captivate the human brain and how digital artists control diffusion lighting.",
    content: "Color isn't merely decorative — it directs narrative flow and viewer emotional response. By anchoring your generative workflows in classical Renaissance gamut masks and applying post-diffusion chromatic curve grading, you can transform flat AI outputs into museum-grade digital artwork.",
    coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    author: {
      name: "Elena Rostova",
      role: "Digital Colorist",
      avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    },
    readTime: "7 min read",
    publishedAt: "2026-08-18",
    category: "Design",
    tags: ["Color Theory", "Generative AI", "Aesthetics", "Creative"],
  },
  {
    id: "blog-3",
    title: "Monetizing Independent Digital Art in 2026: The Creator Blueprint",
    slug: "monetizing-independent-digital-art-2026",
    excerpt: "A tactical guide for independent illustrators, 3D artists, and UI designers building sustainable collector communities.",
    content: "The era of speculative bubbles has matured into genuine patronage and collectible digital ownership. Artists who succeed today combine limited edition drops, interactive web showcase experiences, and community access perks.",
    coverImage: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    author: {
      name: "Aria Sterling",
      role: "Founder & Curator",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    },
    readTime: "4 min read",
    publishedAt: "2026-08-04",
    category: "Insights",
    tags: ["Creator Economy", "Marketplace", "Portfolio", "Strategy"],
  }
];
